function Hd = filter_bandstop_2
%FILTER_BANDSTOP_2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.12 and Signal Processing Toolbox 9.0.
% Generated on: 20-Jan-2026 16:15:19

% Chebyshev Type II Bandstop filter designed using FDESIGN.BANDSTOP.

% All frequency values are in Hz.
Fs = 74.074;  % Sampling Frequency

Fpass1 = 0.4;         % First Passband Frequency
Fstop1 = 0.5;        % First Stopband Frequency
Fstop2 = 1.25;         % Second Stopband Frequency
Fpass2 = 1.3;        % Second Passband Frequency
Apass1 = 0.5;         % First Passband Ripple (dB)
Astop  = 60;          % Stopband Attenuation (dB)
Apass2 = 1;           % Second Passband Ripple (dB)
match  = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.bandstop(Fpass1, Fstop1, Fstop2, Fpass2, Apass1, Astop, ...
                      Apass2, Fs);
Hd = design(h, 'cheby2', 'MatchExactly', match);

% [EOF]
