function Hd = filter_lowpass_07
%FILTER_LOWPASS_07 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.12 and Signal Processing Toolbox 9.0.
% Generated on: 15-Jan-2026 15:20:18

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = 74;  % Sampling Frequency

Fpass = 0.6;         % Passband Frequency
Fstop = 0.9;         % Stopband Frequency
Apass = 0.001;       % Passband Ripple (dB)
Astop = 1;           % Stopband Attenuation (dB)
match = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
